version: "3.9"
services:

  backend:
    image: ldm/backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8601:8601
      
    shm_size: 30gb
    container_name: backend
    volumes:
      - ./data:/app/data
      - ./ldm:/app/ldm
      - ./configs:/app/configs
      - ./assets:/app/assets
      - ./models:/app/models
      - ./scripts:/app/scripts

    env_file: 
      - .env
    deploy:
      resources:
         reservations:
           devices:
           - driver: nvidia
             count: 'all'
             capabilities: [gpu]

    command: bash -c "conda activate ldm; tail -F nothing;"
  